import { test, expect } from '@playwright/test';

test.describe('Live Flow — Admin → Storefront → Cart → Stripe', () => {
  test('Admin Product Upload & Storefront Discovery', async ({ page }) => {
    // Phase 2.1 — Admin Product Creation
    await page.goto('https://website-template-lovat-nine.vercel.app/admin/products');
    await expect(page.locator('h1, h2, text=Admin')).toBeVisible();

    // Fill Add Product form
    await page.fill('input[name="name"], input[placeholder*="Name"], input[type="text"]', 'Playwright Automated Smartwatch');
    await page.fill('input[name="price"], input[placeholder*="Price"], input[type="number"]', '49.99');
    await page.fill('textarea[name="description"], textarea', 'Automated end-to-end test item generated by Playwright.');

    // Submit and verify no 500
    await page.click('button[type="submit"], button:has-text("Add")');
    await expect(page.locator('text=Success, text=Product created, text=Added')).toBeVisible({ timeout: 10000 }).catch(() => {
      // If success message not present, verify table updated instead
      expect(page.locator('text=Playwright Automated Smartwatch')).toBeVisible({ timeout: 8000 });
    });

    // Phase 2.2 — Storefront Discovery
    await page.goto('https://website-template-lovat-nine.vercel.app/');
    await expect(page.locator('text=$49.99')).toBeVisible({ timeout: 10000 });
    await expect(page.locator('text=Playwright Automated Smartwatch')).toBeVisible({ timeout: 10000 });

    // Click product to detail
    await page.locator('a', { hasText: 'Playwright Automated Smartwatch' }).first().click();
    await expect(page).toHaveURL(/store\/playwright-automated-smartwatch/);

    // Phase 2.3 — Cart & Quantity
    await page.locator('button:has-text("Add to Cart"), button:has-text("Add")').click();
    await page.goto('https://website-template-lovat-nine.vercel.app/cart');
    await expect(page.locator('text=Playwright Automated Smartwatch')).toBeVisible();
    await expect(page.locator('text=$49.99')).toBeVisible();

    // Increase quantity to 2
    await page.locator('button:has-text("+"), button[aria-label="increase"]').click();
    await expect(page.locator('text=$99.98')).toBeVisible({ timeout: 5000 });
  });

  test('Mobile Viewport Responsive Audit', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto('https://website-template-lovat-nine.vercel.app/');
    await expect(page.locator('nav, header, button')).toBeVisible();
    await page.goto('https://website-template-lovat-nine.vercel.app/admin');
    await expect(page.locator('text=Admin Dashboard')).toBeVisible();
    await page.goto('https://website-template-lovat-nine.vercel.app/cart');
    await expect(page.locator('text=Your Cart, text=Subtotal')).toBeVisible();
  });

  test('Stripe Checkout Intercept & Webhook', async ({ page }) => {
    // Add item to cart first
    await page.goto('https://website-template-lovat-nine.vercel.app/');
    await page.locator('button:has-text("Add to Cart")').first().click();
    await page.goto('https://website-template-lovat-nine.vercel.app/cart');

    // Intercept checkout request
    const checkoutResponse = await page.waitForResponse(resp =>
      resp.url().includes('/api/checkout') && resp.status() === 200 || resp.status() === 302,
      { timeout: 10000 }
    ).catch(() => null);

    expect(checkoutResponse).not.toBeNull();
  });
});
