import { test, expect } from '@playwright/test';

test.describe('Live Flow: Admin Product Upload & Storefront', () => {
  test('Admin creates product, storefront discovers and navigates to it', async ({ page }) => {
    // 1. Admin Product Creation Action
    await page.goto('https://website-template-lovat-nine.vercel.app/admin/products');
    await expect(page.locator('text=Product Inventory')).toBeVisible();

    await page.getByRole('button', { name: /\+ Product/i }).click();
    await expect(page.getByRole('heading', { name: /Add Product/i })).toBeVisible();

    await page.getByLabel(/name/i).fill('Playwright Automated Smartwatch');
    await page.getByLabel(/price/i).fill('49.99');

    // Category selection: Try to select 'Gadgets' or create it.
    // For this test, we assume 'Gadgets' might exist or we'll just pick the first available.
    // If it's a select dropdown:
    await page.locator('select').first().selectOption({ label: 'Gadgets' }).catch(() => {
        // Fallback if Gadgets doesn't exist: just pick first
        page.locator('select').first().selectOption({ index: 1 });
    });

    await page.getByLabel(/description/i).fill('Automated end-to-end test item generated by Playwright.');

    // Submit the form
    await page.getByRole('button', { name: /add product/i }).click();

    // Verify success (checking for absence of error messages and presence of new product in table)
    // We wait for the network/revalidation to settle.
    await page.waitForTimeout(3000);
    await expect(page.locator('text=Playwright Automated Smartwatch')).toBeVisible();

    // 2. Storefront Product Discovery Action
    await page.goto('/');
    await expect(page.locator('text=Playwright Automated Smartwatch')).toBeVisible();
    // Check formatted price $49.99
    await expect(page.locator('text=$49.99')).toBeVisible();

    // Click the product card
    // Usually, the product card is a link or contains a link.
    await page.locator('text=Playwright Automated Smartwatch').click();

    // Verify navigation to product detail page
    await expect(page).toHaveURL('https://website-template-lovat-nine.vercel.app/store/playwright-automated-smartwatch');
    await expect(page.locator('h1')).toContainText('Playwright Automated Smartwatch');

    // 3. Cart & Quantity Modification Action
    await page.getByRole('button', { name: /add to cart/i }).click();
    await page.goto('/cart');

    await expect(page.locator('text=Playwright Automated Smartwatch')).toBeVisible();
    await expect(page.locator('text=$49.99')).toBeVisible();

    // Increase quantity to 2
    // Assuming a button with '+' or an input
    const quantityPlusBtn = page.locator('button:has-text("+")').first();
    await quantityPlusBtn.click();

    // Verify subtotal recalculates to $99.98
    // We look for the subtotal element
    await expect(page.locator('text=$99.98')).toBeVisible();
  });
});

test.describe('Stripe & Checkout Flow', () => {
  test('Checkout redirects to Stripe and simulates successful order', async ({ page }) => {
    await page.goto('/');
    await page.getByRole('button', { name: /Add to Cart/i }).first().click();
    await page.goto('/cart');

    // 1. Initiate Checkout Flow
    await page.getByRole('button', { name: /proceed to checkout/i }).click();

    // 2. Verify redirect to Stripe
    // Note: In a real CI environment, we might mock this or use a specific test URL.
    // Here we check if the URL contains stripe.com
    await page.waitForURL(/.*stripe\.com.*/);
    console.log('Successfully redirected to Stripe:', page.url());
  });
});
